<!DOCTYPE annotation [
		<!ELEMENT annotation (folder|filename|path|source|size|segmented|object)*>
		<!ATTLIST annotation
				verified CDATA #REQUIRED>
		<!ELEMENT folder (#PCDATA)>
		<!ELEMENT filename (#PCDATA)>
		<!ELEMENT path (#PCDATA)>
		<!ELEMENT source (database)*>
		<!ELEMENT database (#PCDATA)>
		<!ELEMENT size (width|height|depth)*>
		<!ELEMENT width (#PCDATA)>
		<!ELEMENT height (#PCDATA)>
		<!ELEMENT depth (#PCDATA)>
		<!ELEMENT segmented (#PCDATA)>
		<!ELEMENT object (name|pose|truncated|difficult|bndbox)*>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT pose (#PCDATA)>
		<!ELEMENT truncated (#PCDATA)>
		<!ELEMENT difficult (#PCDATA)>
		<!ELEMENT bndbox (xmin|ymin|xmax|ymax)*>
		<!ELEMENT xmin (#PCDATA)>
		<!ELEMENT ymin (#PCDATA)>
		<!ELEMENT xmax (#PCDATA)>
		<!ELEMENT ymax (#PCDATA)>
		]>
<annotation verified="yes">
	<folder>new</folder>
	<filename>alabama.jpg</filename>
	<path>C:\Users\jerry\Documents\GitHub\OCR\img\resized\img\new\alabama.jpg</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>823</width>
		<height>516</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>id_type</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>1</difficult>
		<bndbox>
			<xmin>265</xmin>
			<ymin>28</ymin>
			<xmax>555</xmax>
			<ymax>58</ymax>
		</bndbox>
	</object>
	<object>
		<name>State_Name</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>1</difficult>
		<bndbox>
			<xmin>332</xmin>
			<ymin>61</ymin>
			<xmax>757</xmax>
			<ymax>120</ymax>
		</bndbox>
	</object>
	<object>
		<name>NO.</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>1</difficult>
		<bndbox>
			<xmin>396</xmin>
			<ymin>161</ymin>
			<xmax>535</xmax>
			<ymax>189</ymax>
		</bndbox>
	</object>
	<object>
		<name>CLASS</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>1</difficult>
		<bndbox>
			<xmin>655</xmin>
			<ymin>162</ymin>
			<xmax>678</xmax>
			<ymax>190</ymax>
		</bndbox>
	</object>
	<object>
		<name>DOB</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>1</difficult>
		<bndbox>
			<xmin>359</xmin>
			<ymin>192</ymin>
			<xmax>530</xmax>
			<ymax>220</ymax>
		</bndbox>
	</object>
	<object>
		<name>EXP</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>1</difficult>
		<bndbox>
			<xmin>612</xmin>
			<ymin>193</ymin>
			<xmax>780</xmax>
			<ymax>221</ymax>
		</bndbox>
	</object>
	<object>
		<name>Last_Name</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>1</difficult>
		<bndbox>
			<xmin>289</xmin>
			<ymin>249</ymin>
			<xmax>747</xmax>
			<ymax>276</ymax>
		</bndbox>
	</object>
	<object>
		<name>Address</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>1</difficult>
		<bndbox>
			<xmin>286</xmin>
			<ymin>285</ymin>
			<xmax>741</xmax>
			<ymax>305</ymax>
		</bndbox>
	</object>
	<object>
		<name>City_State_Zip</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>1</difficult>
		<bndbox>
			<xmin>289</xmin>
			<ymin>306</ymin>
			<xmax>713</xmax>
			<ymax>326</ymax>
		</bndbox>
	</object>
	<object>
		<name>RESTRICTIONS</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>1</difficult>
		<bndbox>
			<xmin>675</xmin>
			<ymin>326</ymin>
			<xmax>694</xmax>
			<ymax>354</ymax>
		</bndbox>
	</object>
	<object>
		<name>ISS</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>1</difficult>
		<bndbox>
			<xmin>319</xmin>
			<ymin>354</ymin>
			<xmax>489</xmax>
			<ymax>383</ymax>
		</bndbox>
	</object>
	<object>
		<name>SEX</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>1</difficult>
		<bndbox>
			<xmin>567</xmin>
			<ymin>356</ymin>
			<xmax>587</xmax>
			<ymax>376</ymax>
		</bndbox>
	</object>
	<object>
		<name>Height</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>1</difficult>
		<bndbox>
			<xmin>637</xmin>
			<ymin>356</ymin>
			<xmax>689</xmax>
			<ymax>379</ymax>
		</bndbox>
	</object>
	<object>
		<name>EYES</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>1</difficult>
		<bndbox>
			<xmin>749</xmin>
			<ymin>354</ymin>
			<xmax>792</xmax>
			<ymax>379</ymax>
		</bndbox>
	</object>
	<object>
		<name>HAIR</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>1</difficult>
		<bndbox>
			<xmin>748</xmin>
			<ymin>381</ymin>
			<xmax>794</xmax>
			<ymax>404</ymax>
		</bndbox>
	</object>
	<object>
		<name>WEIGHT</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>1</difficult>
		<bndbox>
			<xmin>638</xmin>
			<ymin>381</ymin>
			<xmax>682</xmax>
			<ymax>404</ymax>
		</bndbox>
	</object>
	<object>
		<name>First_Name</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>1</difficult>
		<bndbox>
			<xmin>289</xmin>
			<ymin>221</ymin>
			<xmax>735</xmax>
			<ymax>249</ymax>
		</bndbox>
	</object>
</annotation>
